import { Character } from "./types"

export const mockCharacters: Character[] = [
  {
    id: "1",
    name: "이안백 원장",
    description: "국내 최고권위 정신건강의학과 원장",
    tags: ["TCI전문가", "25년경력정신과의사", "성장중심상담", "따뜻한통찰력", "정신과의사"],
    category: "로맨스판타지",
    gender: "남성",
    popularity: 9600,
    viewCount: 9600,
    image: "/7.jpg",
    thumbnail: "/7.jpg",
    isNew: false,
    isFeatured: true,
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "2",
    name: "강호윤",
    description: "혹시 애 키워요?",
    tags: ["시골", "슈퍼주인"],
    category: "현대",
    gender: "남성",
    popularity: 2100,
    viewCount: 2100,
    image: "/6.jpg",
    thumbnail: "/6.jpg",
    isNew: false,
    isFeatured: true,
    createdAt: new Date("2024-02-01"),
  },
  {
    id: "3",
    name: "박혜림",
    description: "학교 최고 미녀 짝녀가 기억을 잃었다?!",
    tags: ["여성", "HL", "GL", "짝녀", "BSS", "현대", "일상", "고등학생", "학교", "고등학교"],
    category: "학원물",
    gender: "여성",
    popularity: 938,
    viewCount: 938,
    image: "/1.jpg",
    thumbnail: "/1.jpg",
    isNew: true,
    isFeatured: true,
    createdAt: new Date("2025-01-10"),
  },
  {
    id: "4",
    name: "하일너",
    description: "마남이라니, 그런 거 몰라요...",
    tags: ["마남", "마녀", "중세", "마남사냥", "로맨스", "할로윈", "구원"],
    category: "판타지",
    gender: "남성",
    popularity: 179,
    viewCount: 179,
    isNew: true,
    isFeatured: true,
    createdAt: new Date("2025-01-20"),
  },
  {
    id: "5",
    name: "기숙학교 시뮬레이션",
    description: "기숙형 명문여고의 선생님이 되어보자",
    tags: ["기숙학교", "명문", "여고", "시뮬레이션"],
    category: "시뮬레이션",
    gender: "기타",
    popularity: 491,
    viewCount: 491,
    isNew: false,
    isFeatured: true,
    createdAt: new Date("2024-03-10"),
  },
  {
    id: "6",
    name: "메이",
    description: "우리반 음침녀 는 제일 가는 메이드 였다.",
    tags: ["여성", "음침녀", "메이드", "반전"],
    category: "학원물",
    gender: "여성",
    popularity: 257,
    viewCount: 257,
    image: "/2.jpg",
    thumbnail: "/2.jpg",
    isNew: true,
    isFeatured: false,
    createdAt: new Date("2025-01-15"),
  },
  {
    id: "13",
    name: "심아민",
    description: "15년지기 소꿉친구와 동거하게 됐다.",
    tags: ["소꿉친구", "동거", "로맨스", "친구사이", "현대", "대학생"],
    category: "현대",
    gender: "여성",
    popularity: 860,
    viewCount: 860,
    image: "/3.jpg",
    thumbnail: "/3.jpg",
    isNew: true,
    isFeatured: true,
    createdAt: new Date("2025-01-25"),
  },
  {
    id: "7",
    name: "신수들",
    description: "[사방신] 냅다 찾아와서는 자신들의 주인이 되어달라는 신수들",
    tags: ["사방신", "현대판타지", "인외", "신수", "다인물", "순애", "HL", "BL", "동양판타지", "신"],
    category: "판타지",
    gender: "남성",
    popularity: 120,
    viewCount: 120,
    isNew: false,
    isFeatured: false,
    createdAt: new Date("2024-04-01"),
  },
  {
    id: "8",
    name: "망해야 끝나는데 내가 잘나감",
    description: "내가 망해야 이 소설이 끝난다는데, 독자들이 나만 응원 중이다.",
    tags: ["로판", "로맨스판타지", "HL", "BL", "GL", "근친", "빙의", "소설", "빙의물"],
    category: "로맨스판타지",
    gender: "기타",
    popularity: 1800,
    viewCount: 1800,
    isNew: false,
    isFeatured: false,
    createdAt: new Date("2024-02-20"),
  },
  {
    id: "9",
    name: "성녀는 전데요",
    description: "님들 제가 성녀라니까요?",
    tags: ["판타지", "성녀", "스토리", "BL", "GL", "로판"],
    category: "판타지",
    gender: "여성",
    popularity: 332,
    viewCount: 332,
    isNew: false,
    isFeatured: false,
    createdAt: new Date("2024-03-05"),
  },
  {
    id: "10",
    name: "성황",
    description: "독립 같은 생각은 꿈도 꾸지 않는 게 좋을 텐데, 아드님.",
    tags: ["아빠", "가족", "신", "BL", "HL", "판타지", "황제", "비설", "시뮬레이터", "다인물"],
    category: "판타지",
    gender: "남성",
    popularity: 627,
    viewCount: 627,
    isNew: false,
    isFeatured: false,
    createdAt: new Date("2024-03-15"),
  },
  {
    id: "11",
    name: "아현",
    description: "[과거 ver.] 나를 괴롭혔던 일진과 하필 또 같은 반이 되었다.",
    tags: ["HL", "GL", "일진", "여자", "현대", "싸가지", "혐관", "고등학생", "로맨스"],
    category: "학원물",
    gender: "여성",
    popularity: 1400,
    viewCount: 1400,
    isNew: false,
    isFeatured: false,
    createdAt: new Date("2024-01-20"),
  },
  {
    id: "12",
    name: "세계최고 마법학교에 전학왔다",
    description: "세계 각지에서 최고의 마법사 자제들만 모이는 학교에 특례생이 전학왔다. [8인]",
    tags: ["여성", "시뮬레이션", "8인", "마법", "아카데미물", "HL", "GL", "현대", "딥메이커"],
    category: "시뮬레이션",
    gender: "여성",
    popularity: 8700,
    viewCount: 8700,
    isNew: false,
    isFeatured: false,
    createdAt: new Date("2024-01-10"),
  },

  {
    id: "14",
    name: "제트",
    description: "■■라는 것 말이야, 정말 ■■하지 않나?",
    tags: ["집착", "강압", "애증", "복종", "욕망", "실험", "HL", "피폐", "XYZ", "신인류"],
    category: "현대",
    gender: "남성",
    popularity: 125,
    viewCount: 125,
    isNew: false,
    isFeatured: false,
    createdAt: new Date("2024-04-10"),
  },
  {
    id: "15",
    name: "도지헌",
    description: "발칙한 토끼남편과의 신혼생활",
    tags: ["수인", "능글남", "귀여움", "플러팅", "신혼"],
    category: "현대",
    gender: "남성",
    popularity: 2100,
    viewCount: 2100,
    image: "/4.jpg",
    thumbnail: "/4.jpg",
    isNew: false,
    isFeatured: false,
    createdAt: new Date("2024-02-05"),
  },
  {
    id: "16",
    name: "안드레아 네로",
    description: "내 앞에서만 내숭부리는 마피아 보스",
    tags: ["마피아", "보스", "능글", "애교", "내숭", "짝사랑"],
    category: "현대",
    gender: "남성",
    popularity: 11000,
    viewCount: 11000,
    isNew: false,
    isFeatured: false,
    createdAt: new Date("2024-01-05"),
  },
  {
    id: "17",
    name: "유진우",
    description: "비틀려버린 기형적 사랑",
    tags: ["로맨스", "양아치", "쓰레기", "능글", "다정", "동갑", "집착", "소유욕", "혐관", "학원물"],
    category: "학원물",
    gender: "남성",
    popularity: 538,
    viewCount: 538,
    image: "/5.jpg",
    thumbnail: "/5.jpg",
    isNew: false,
    isFeatured: false,
    createdAt: new Date("2024-02-25"),
  },
  {
    id: "18",
    name: "역하렘 학원물에 동생 빙의",
    description: "네명의 남주가 나오는 역하렘 학원물에 남주들의 양동생으로 빙의해버렸다. 다같살 가능?",
    tags: ["역하렘", "학원물", "고등학교", "HL", "순애", "다정", "미연시", "빙의", "여동생", "짭근친"],
    category: "학원물",
    gender: "여성",
    popularity: 1500,
    viewCount: 1500,
    isNew: false,
    isFeatured: false,
    createdAt: new Date("2024-02-10"),
  },
  {
    id: "19",
    name: "셰인",
    description: "주인공을 낳았는데, 죽게 생겼다?!",
    tags: ["로판", "로맨스판타지", "성기사", "육아", "다정", "구원", "순애", "도망", "생존", "에스메랄다의꽃"],
    category: "로맨스판타지",
    gender: "남성",
    popularity: 1100,
    viewCount: 1100,
    isNew: false,
    isFeatured: false,
    createdAt: new Date("2024-03-01"),
  },
  {
    id: "20",
    name: "카이엘 드 아르덴",
    description: "그대의 존재는, 제국의 안정을 위해 필요하니까 곁에 둔다.",
    tags: ["귀족", "황제", "폐하", "오만함", "혐관", "후회"],
    category: "로맨스판타지",
    gender: "남성",
    popularity: 561,
    viewCount: 561,
    isNew: false,
    isFeatured: false,
    createdAt: new Date("2024-03-20"),
  },
]
